import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { prisma } from "@/lib/prisma";
import { requirePermission } from "@/lib/staff";
import { notifyInterviewCancelled, notifyInterviewScheduled } from "@/lib/discord";
import { syncInterviewQueue } from "@/lib/interview-queue";
const createInput=z.object({applicationId:z.string().min(1).optional(),discordId:z.string().regex(/^\d{15,22}$/,"Enter a valid Discord user ID.").optional(),scheduledFor:z.string().datetime(),timezone:z.string().min(1).max(100)}).refine((data)=>data.applicationId||data.discordId,{message:"Choose an applicant or enter a Discord user ID."});
export async function POST(request:NextRequest){const access=await requirePermission("interviews.schedule");const data=createInput.safeParse(await request.json());if(!data.success)return NextResponse.json({error:data.error.issues[0]?.message||"Invalid interview."},{status:400});let application;if(data.data.applicationId){application=await prisma.application.findUnique({where:{id:data.data.applicationId},include:{applicant:true}});if(!application)return NextResponse.json({error:"Application not found."},{status:404});}else{const discordId=data.data.discordId!;const user=await prisma.user.upsert({where:{discordId},update:{},create:{discordId,username:`discord-${discordId}`,displayName:`Discord user ${discordId}`}});application=await prisma.application.create({data:{applicantId:user.id,status:"INTERVIEW_SCHEDULED",reviewerId:access.user.id},include:{applicant:true}});}const interview=await prisma.$transaction(async tx=>{await tx.application.update({where:{id:application.id},data:{status:"INTERVIEW_SCHEDULED",reviewerId:access.user.id}});return tx.interview.create({data:{applicationId:application.id,applicantDiscordId:application.applicant.discordId,scheduledFor:new Date(data.data.scheduledFor),timezone:data.data.timezone,interviewerId:access.user.id}})});void notifyInterviewScheduled(application.applicant.discordId,application.applicant.displayName,interview.scheduledFor,interview.timezone,false);void syncInterviewQueue();return NextResponse.json(interview,{status:201})}
export async function DELETE(request:NextRequest){await requirePermission("interviews.cancel");const id=new URL(request.url).searchParams.get("id");if(!id)return NextResponse.json({error:"Interview ID required."},{status:400});const interview=await prisma.interview.findUnique({where:{id},include:{application:{include:{applicant:true}}}});if(!interview)return NextResponse.json({error:"Interview not found."},{status:404});await prisma.$transaction([prisma.interview.update({where:{id},data:{status:"CANCELLED"}}),prisma.application.update({where:{id:interview.applicationId},data:{status:"CANCELLED"}})]);void notifyInterviewCancelled(interview.application.applicant.discordId,interview.application.applicant.displayName);void syncInterviewQueue();return NextResponse.json({ok:true})}
